import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {defaults} from '../public/model.js';
const source=await readFile(new URL('../dist/server/index.js',import.meta.url),'utf8');const {default:worker}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const original=globalThis.fetch;let forwarded;
const request=d=>new Request('https://test.local/api/analyse',{method:'POST',headers:{origin:'https://test.local','Content-Type':'application/json'},body:JSON.stringify(d)});
globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);if(body.tools){assert.equal(body.tool_choice,'required');assert.deepEqual(body.tools,[{type:'web_search'}]);assert.equal('brief' in JSON.parse(body.input),false);return new Response(JSON.stringify({output:[{type:'web_search_call',status:'completed',action:{sources:[{url:'https://example.com/plv',title:'Catalogue PLV'}]}},{content:[{type:'output_text',text:'Comparable public : contexte simulé.'}]}]}));}assert.match(body.instructions,/Ne demande JAMAIS budget/);const input=JSON.parse(body.input);forwarded=input.projet||input;const common={questions:['Quel est le budget maximal envisagé ?','Faut-il des portes ou des tiroirs ?','Qui prend en charge la pose ?'],justification:'Analyse simulée.',pistes:'À préciser.',argumentaire:'Hypothèses à confirmer.'};return new Response(JSON.stringify({output:[{content:[{type:'output_text',text:JSON.stringify({...common,low:null,target:null,high:null})}]}]}));};
try{
 for(const mode of ['Avec produits','Sans produit']){const answers=[{question:'Faut-il des portes ou des tiroirs ?',answer:'Portes pour toute la série.'}];const response=await worker.fetch(request({...defaults,containsProducts:mode,answers}),{OPENAI_API_KEY:'test'});assert.equal(response.status,200);const data=await response.json();assert.deepEqual(data.questions,['Qui prend en charge la pose ?']);assert.equal(data.result,null);assert.ok(data.questions.every(q=>!/budget/i.test(q)));assert.ok(data.questions.every(q=>q!==answers[0].question));assert.ok(!/budget maximal/.test(data.text));assert.deepEqual(forwarded.answers,answers);}
 const response=await worker.fetch(request({...defaults,answers:[{question:'Test',answer:'x'.repeat(3001)}]}),{OPENAI_API_KEY:'test'});assert.equal(response.status,400);
 const manifestResponse=await worker.fetch(new Request('https://test.local/manifest.webmanifest'),{});assert.equal(manifestResponse.headers.get('content-type'),'application/manifest+json');const manifest=await manifestResponse.json();assert.equal(manifest.display,'standalone');assert.deepEqual(manifest.icons.map(i=>i.sizes),['192x192','512x512']);for(const icon of manifest.icons){const r=await worker.fetch(new Request('https://test.local'+icon.src),{});assert.equal(r.status,200);const bytes=new Uint8Array(await r.arrayBuffer());assert.equal(bytes[0],137);}
 console.log('Questions budgétaires filtrées dans les deux modes, réponses transmises, questions répondues écartées, validation et manifeste/installabilité préparés.');
}finally{globalThis.fetch=original;}
